### ISSUE TITLE
Invalid use of readuInt

### ISSUE THREAD

**Issue by mangoose002** [WinteryFox/FBXImport#1]
Hi,

It seems that you use readuInt everytime.
Whatever the version is, the use of stream.read<uint32_t>(); is mandatory to have the file loader properly in some cases:

Some parts need to be rewritten:
std::vector<T> Decoder::readArray() {
        size_t arraySize = stream.read<uint32_t>();
        size_t encoding = stream.read<uint32_t>();
        size_t completeLength = stream.read<uint32_t>();

instead of

std::vector<T> Decoder::readArray() {
        size_t arraySize = readuInt();
        size_t encoding = readuInt();
        size_t completeLength = readuInt();

case 'R': {
                    const auto &data = stream.read<char>(stream.read<uint32_t>());
instead of
case 'R': {
                    const auto &data = stream.read<char>(readuInt(););

case 'S': {
                    const auto &data = stream.read<char>(stream.read<uint32_t>());
instead of
case 'S': {
                    const auto &data = stream.read<char>(readuInt(););

With thoses fixes, your code can read any file

**Comment by WinteryFox** [comment]
Thanks for the tip, feel free to PR it since it is your work!

**Comment by WinteryFox** [comment]
Fixed in 3e03847
